# Generated by Django 2.2.6 on 2021-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_auto_20210616_0052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="Адрес страницы"
            ),
        ),
    ]
