# Generated by Django 2.2.6 on 2021-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20210617_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Адрес страницы"),
        ),
    ]
